jwt:
  secret: LRXHV49MAFSAXB79WJV3IIQR  #JWT密钥
  expiration: 864000000             #JWT过期时间（1000天）

spring:
   datasource:
      url: jdbc:mysql://47.97.252.72:3307/review?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
      username: sast
      password: sast_forever
#   redis:
#     host: 127.0.0.1
#     port: 6379