jwt:
  secret: jwt  # JWT密钥
  expiration: 864000000             # JWT过期时间（毫秒）

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/review
    username: root
    password: 111111

  data:
    redis:
      host: localhost
      port: 6379

file:
  OSS:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: mock-access-key
    accessKeySecret: mock-access-secret
    bucketName: mock-bucket
    publicFolder: public
    privateFolder: private
    uploadExpiredTime: 60
    downloadExpiredTime: 60
    bucket-url-prefix: https://mock-bucket.oss-cn-hangzhou.aliyuncs.com/
server:
  port: 9090
